---
name: lint

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
# yamllint disable-line rule:truthy
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  # This workflow contains a single job called "build"
  linter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: ./.github/actions/hadolint
        with:
          file: Dockerfile
      - name: Lint helper.sh
        uses: ./.github/actions/shellcheck
        with:
          file: helper.sh
      - name: Lint .github/workflows/main.yml
        uses: ./.github/actions/yamllint
        with:
          file: .github/workflows/main.yml
      - name: Lint .github/actions/yamllint/action.yml
        uses: ./.github/actions/yamllint
        with:
          file: .github/actions/yamllint/action.yml
