---
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#name
name: lint

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# yamllint disable-line rule:truthy
on: [push, pull_request]

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  linter:
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: ./.github/actions/hadolint
        with:
          file: Dockerfile
      - name: Lint helper.sh
        uses: ./.github/actions/shellcheck
        with:
          file: helper.sh
      - name: Lint .github/workflows/main.yml
        uses: ./.github/actions/yamllint
        with:
          file: .github/workflows/main.yml
      - name: Lint .github/actions/yamllint/action.yml
        uses: ./.github/actions/yamllint
        with:
          file: .github/actions/yamllint/action.yml
