---
name: lint

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  # This workflow contains a single job called "build"
  linter:
    # The type of runner that the job will run on
    runs-on: [self-hosted,container,amd64,fedora31]

    steps:
      - name: Lint Dockerfile
        uses: actions/hadolint
        with:
          file: Dockerfile
      - name: Lint helper.sh
        uses: actions/shellcheck
        with:
          file: helper.sh
      - name: Lint helper.sh
        uses: actions/shellcheck
        with:
          file: helper.sh
      